### ISSUE TITLE
Uploading and Downloading from Angular

### ISSUE THREAD

**Issue by amandafrazier** [aldmbmtl/hfx-site#16]
*Mix of backend stuff and front end stuff.*

Create a button that says upload and download. Need it to bring up either a file browser or allow the user to drag and drop files.
From there-figure out how to take the information and update it to an S3 bucket.

**Comment by dempseyc** [comment]
Where should this button be? What are we uploading and downloading?  Projects?

**Comment by aldmbmtl** [comment]
This has been addressed and finished as of 2 days ago. Just have not closed it out. Thanks!
